server:
  port: 8083
  tomcat:
    uri-encoding: utf-8
#    max-http-post-size: -1
  max-http-header-size: 4048576
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: test
#log
logging:
  config: classpath:logback.xml