spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3s
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1s
    password: sykean123
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/hmhc_db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true 
      username: root
      password: 123456
      initialSize: 10
      minIdle: 30
      maxActive: 200
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat
#mapper debug
logging:
  level:
    com.sykean.hmhc: debug
# file server
fastdfs:
  tracker-server: 192.168.0.166:22122
  file-prefix: http://192.168.0.166:80/
# iris server
irisserverurl:
  irisurl: http://192.168.0.166:8090
  